[package]
name = "etheroit/profileservice"
version = "1.2.0"
license = "Apache License 2.0"
authors = ["loleris"]
description = "loleris' ProfileService forked for wally"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"